name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x

    - name: Run tests
      run: go test -v ./...

    - name: Build examples
      run: |
        cd builder_example
        go build -o regextable-example .

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        body: |
          ## Changes
          
          See [CHANGELOG.md](https://github.com/sfkleach/regextable/blob/main/CHANGELOG.md) for full details. This changelog is maintained manually.
          
          ## Installation
          
          ```bash
          go get github.com/sfkleach/regextable@${{ github.ref_name }}
          ```
        draft: false
        prerelease: false

